---
# Metadata
site_name: Hudater Docs
site_description: Centralized documentation for docker and more...
site_author: Hudater
site_url: https://hudater.github.io
edit_uri: edit/main/docs/
docs_dir: docs

repo_name: Hudater/hudater.github.io
repo_url: https://github.com/Hudater/hudater.github.io


# Theme setup
theme:
  name: material
  language: en
  custom_dir: overrides
  # custom_dir: overrideslaskjflk
  logo: assets/logo.jpg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Encode Sans Expanded"

# Required for tags to function
markdown_extensions:
  - admonition
  - meta
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - tags:
      tags_file: about/tags.md

# Navigation setup
nav:
  - Home: index.md
  - Media:
    - Sonarr:
      - Setup: media/sonarr.md
    - Radarr: media/radarr.md
  - Networking:
    - Architecture: networking/architecture.md
  - Linux:
    - Arch: linux/arch.md
  - About:
    - Tags: about/tags.md


# Footer section
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hudater