---
# Metadata
site_name: Hudater Docs
site_description: Centralized documentation for docker and more...
site_author: Hudater
site_url: https://hudater.github.io
# edit_uri: edit/master/docs/
# docs_dir: docs

repo_name: Hudater/hudater.github.io
repo_url: https://github.com/Hudater/hudater.github.io


# Theme setup
theme:
  name: material
  language: en
  logo: assets/logo.jpeg
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Encode Sans Expanded"


# Navigation setup
nav:
  - Home: index.md
  - Media:
    - Sonarr:
      - Setup: media/sonarr.md
    - Radarr: media/radarr.md
  - Networking:
    - Architecture: networking/architecture.md
  - Linux:
    - Arch: linux/arch.md


# Footer section
copyright: Copyright &copy; 2022 Hudater

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hudater