---
site_name: Hudater Docs
site_description: Centralized documentation for docker and more...
site_author: Hudater
site_url: https://hudater.github.io
# edit_uri: edit/master/docs/
# docs_dir: docs

repo_name: Hudater/hudater.github.io
repo_url: https://github.com/Hudater/hudater.github.io

copyright: Copyright &copy; 2022 Hudater

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Encode Sans Expanded"
